### PR TITLE
CSS: Fix string token value on special string escapes

### LINKED ISSUE #222: CSS Processor string token values mishandle backslash-newline
In CSS `<string>` token values, `WordPress\DataLiberation\CSS\CSSProcessor::get_token_value()` reports an incorrect token value for `\` + `\n` (it should be ignored in the token value).

[See the rules for consuming a string token](https://www.w3.org/TR/css-syntax-3/#consume-string-token):

> Repeatedly consume the [next input code point](https://www.w3.org/TR/css-syntax-3/#next-input-code-point) from the stream:
> 
> …
>
> U+005C REVERSE SOLIDUS (`\`)
> …
>   - Otherwise, if the [next input code point](https://www.w3.org/TR/css-syntax-3/#next-input-code-point) is a newline, consume it.
> …

Related to #223.

---

Demo

```php
$p = WordPress\DataLiberation\CSS\CSSProcessor::create( "'str\\\ning'" );
$p->next_token();
assert( $p->get_token_type() === WordPress\DataLiberation\CSS\CSSProcessor::TOKEN_STRING );
assert( $p->get_token_value() === 'string', 'Expected "string", got ' . var_export( $p->get_token_value(), true ) );
```

Will throw `AssertionError: Expected "string", got 'str\\\ning'`.

---

## Example of string value equality

[`"A\\nB" === "AB"`](https://software.hixie.ch/utilities/js/live-dom-viewer/?This%20should%20render%20with%20a%20fancy%20font%2C%20%3Ci%3Enot%20monospace%3C%2Fi%3E.%0A%3Cstyle%3E%0A%2F*%20Note%20that%20the%20two%20%22AB%22%20strings%20match.%20*%2F%0Abody%20%7B%20font-family%3A%20%27A%5C%0AB%27%2C%20monospace%3B%7D%0A%40font-face%20%7B%0A%20%20src%3A%20url(https%3A%2F%2Ffonts.gstatic.com%2Fs%2Flobster%2Fv32%2FneILzCirqoswsqX9zoKmM4MwWJU.woff2)%20format(%27woff2%27)%3B%0A%20%20font-family%3A%20%27AB%27%3B%0A%7D%0A%3C%2Fstyle%3E)

```html
This should render with a fancy font, <i>not monospace</i>.
<style>
/* Note that the two "AB" strings match. */
body { font-family: 'A\
B', monospace;}
@font-face {
  src: url(https://fonts.gstatic.com/s/lobster/v32/neILzCirqoswsqX9zoKmM4MwWJU.woff2) format('woff2');
  font-family: 'AB';
}
</style>
```

### LINKED ISSUE #223: CSS Processor string token values mishandle backslash-EOF
In CSS `<string>` token values, `WordPress\DataLiberation\CSS\CSSProcessor::get_token_value()` reports an incorrect token value when `\` is at the end of input.

[See the rules for consuming a string token](https://www.w3.org/TR/css-syntax-3/#consume-string-token):

> Repeatedly consume the [next input code point](https://www.w3.org/TR/css-syntax-3/#next-input-code-point) from the stream:
> 
> …
>
> U+005C REVERSE SOLIDUS (`\`)
>   - If the [next input code point](https://www.w3.org/TR/css-syntax-3/#next-input-code-point) is EOF, do nothing.
> …

Related to #222.

---

Demos

```php
$p = WordPress\DataLiberation\CSS\CSSProcessor::create( "'string\\" );
$p->next_token();
assert( $p->get_token_type() === WordPress\DataLiberation\CSS\CSSProcessor::TOKEN_STRING );
assert( $p->get_token_value() === 'string', 'Expected "string", got ' . var_export( $p->get_token_value(), true ) );
```

Will throw `AssertionError: Expected "string", got 'string�'`.

---

## Example of string value equality

[`"AB" === "AB\{{END-OF-INPUT}}`](https://software.hixie.ch/utilities/js/live-dom-viewer/?This%20should%20render%20with%20a%20fancy%20font%2C%20%3Ci%3Enot%20monospace%3C%2Fi%3E.%0A%3Cstyle%3E%0A%2F*%20Note%20that%20the%20two%20%22AB%22%20strings%20match.%20*%2F%0Abody%20%7B%20font-family%3A%20%27AB%27%2C%20monospace%3B%7D%0A%40font-face%20%7B%0A%20%20src%3A%20url(https%3A%2F%2Ffonts.gstatic.com%2Fs%2Flobster%2Fv32%2FneILzCirqoswsqX9zoKmM4MwWJU.woff2)%20format(%27woff2%27)%3B%0A%20%20font-family%3A%20%27AB%5C)

```html
This should render with a fancy font, <i>not monospace</i>.
<style>
/* Note that the two "AB" strings match. */
body { font-family: 'AB', monospace;}
@font-face {
  src: url(https://fonts.gstatic.com/s/lobster/v32/neILzCirqoswsqX9zoKmM4MwWJU.woff2) format('woff2');
  font-family: 'AB\
```

### PR DESCRIPTION
**Pull request by sirreal**
## Summary

- Fix `\`-newline and `\`-EOF handling in CSS string token value decoding
- Rename `decode_string_or_url` → `decode_range` with a new `bool $string_escapes` parameter for [CSS string token rules (§4.3.5)](https://www.w3.org/TR/css-syntax-3/#consume-string-token): `\`-newline discards both characters (line continuation), `\`-EOF discards the backslash
- Add test coverage for these cases and fix incorrect expected values in the JSON test corpus
- Add `css` test group to allow `vendor/bin/phpunit --group css`

Note that the css test file diverged from the originals in these cases. For example, [see string/0005](https://github.com/romainmenke/css-tokenizer-tests/blob/4cdf29c796003ce1543b9d86bbf27c3b7447bab3/tests/string/0005/tokens.json) where the expected token value is `foo` like in this PR.

- fixes #222
- fixes #223

## Test plan

CI passes. Visually confirm that updated and new tests are correct.

### CODE REVIEW

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 1]
```diff
@@ -632,9 +632,10 @@ public function get_normalized_token(): ?string {
 			return null;
 		}
 
-		return $this->decode_string_or_url(
+		return $this->decode_escapes(
 			$this->token_starts_at,
-			$this->token_length
+			$this->token_length,
+			self::TOKEN_STRING === $this->token_type || self::TOKEN_BAD_STRING === $this->token_type
```
Comment (sirreal) [inline components/DataLiberation/CSS/class-cssprocessor.php]: This diverges from #226 and will need


```diff
-			self::TOKEN_STRING === $this->token_type || self::TOKEN_BAD_STRING === $this->token_type
+			self::TOKEN_STRING === $this->token_type
```

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 2]
```diff
@@ -1581,8 +1603,35 @@ private function decode_string_or_url( int $start, int $length ): string {
...
+						if ( $at < $end && "\n" === $this->css[ $at ] ) {
+							++$at;
+						}
+						continue;
+					}
+				}
+
 				if ( $this->is_valid_escape( $at ) ) {
 					++$at;
 					$decoded .= $this->decode_escape_at( $at, $bytes_consumed );
```
[the remark this answers is not in the document]
Comment (sirreal) [reply components/DataLiberation/CSS/class-cssprocessor.php:1638]: This is a good spot, but not new in this PR: https://github.com/WordPress/php-toolkit/issues/228

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 3]
```diff
@@ -1581,8 +1603,35 @@ private function decode_string_or_url( int $start, int $length ): string {
 
 			$char = $this->css[ $at ];
 
-			// Handle escapes (if enabled).
+			// Handle escapes.
 			if ( '\\' === $char ) {
+				/*
+				 * String tokens have special escape rules per §4.3.5:
+				 * - \-EOF: do nothing (consume the backslash, produce no value).
+				 * - \-newline: consume both (line continuation, produce no value).
```
Comment (adamziel) [inline components/DataLiberation/CSS/class-cssprocessor.php]: @copilot Let's express that as 0x byte sequences with annotations what do they mean. This notation confuses me.

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 4]
```diff
@@ -1539,19 +1551,29 @@ private function consume_ident_start_codepoint( $at ): int {
...
+	 * @param int  $start           Start byte offset.
+	 * @param int  $length          Length of the substring to decode.
+	 * @param bool $string_escapes  Optional, default false. When true, apply special CSS string
+	 *                              token escape rules:
+	 *                                - \-newline is consumed as a line continuation (ignored).
+	 *                                - \-EOF is silently discarded.
+	 * @return string Decoded and normalized string.
 	 */
-	private function decode_string_or_url( int $start, int $length ): string {
+	private function decode_range( int $start, int $length, bool $string_escapes = false ): string {
```
Comment (adamziel) [inline components/DataLiberation/CSS/class-cssprocessor.php:1571]: Nice rename @sirreal!

File: components/DataLiberation/CSS/class-cssprocessor.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (adamziel) [reply components/DataLiberation/CSS/class-cssprocessor.php:1638]: nice. It would be great to explore a fix+test in another pr cc @copilot

[the remark this answers is not in the document]
Comment (sirreal) [reply components/DataLiberation/CSS/class-cssprocessor.php:1638]: Copilot opened #229 already

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 5]
```diff
@@ -1537,19 +1548,29 @@ private function consume_ident_start_codepoint( $at ): int {
...
+	 * │ 'a\r\nb'     │ 'a\nb' │
+	 * │ 'a\0b'       │ 'a�b'  │
+	 * └──────────────┴────────┘
+	 *
+	 * @param int  $start           Start byte offset.
+	 * @param int  $length          Length of the substring to decode.
+	 * @param bool $string_escapes  Optional, default false. When true, apply special CSS string
+	 *                              token escape rules:
+	 *                                - \-newline is consumed as a line continuation (ignored).
+	 *                                - \-EOF is silently discarded.
```
Comment (sirreal) [inline components/DataLiberation/CSS/class-cssprocessor.php]: @copilot This should be consistent with the comment in the body. Below that was changed to use HEX, so lets do that here as well.

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 6]
```diff
@@ -1537,19 +1548,30 @@ private function consume_ident_start_codepoint( $at ): int {
...
+	 * │ 'x\000079 z' │ 'xyz'  │
+	 * │ 'a\r\nb'     │ 'a\nb' │
+	 * │ 'a\0b'       │ 'a�b'  │
+	 * └──────────────┴────────┘
+	 *
+	 * @param int  $start           Start byte offset.
+	 * @param int  $length          Length of the substring to decode.
+	 * @param bool $string_escapes  Optional, default false. When true, apply special CSS string
+	 *                              token escape rules:
+	 *                                - 0x5C (backslash) followed by 0x0A (LF), 0x0C (FF), or 0x0D (CR)
```
Comment (sirreal) [inline components/DataLiberation/CSS/class-cssprocessor.php]: @copilot Both here and below the `CRLF` case in not mentioned.

- Here it would be better to remove the technical details and just say that there are some additional escaping rules the apply only to strings.
- Add the CRLF case to the technical comment in the function body.

**Review by adamziel — APPROVED** [review]
LGTM! The title and description need brushing up since this PR is about more than the documentation, other than that it's great. Thank you!

**Comment by sirreal** [comment]
@copilot Your edits to the PR description have made it worse. Study the changes in this PR and update the PR to provide a relevant description.

It may help to consider the original description:

> ## Summary
> 
> - Fix `\`-newline and `\`-EOF handling in CSS string token value decoding (fixes #222, #223)
> - Rename `decode_string_or_url` → `decode_escapes` with a new `$string_escapes` parameter for [CSS string token rules (§4.3.5)](https://www.w3.org/TR/css-syntax-3/#consume-string-token): `\`-newline discards both characters (line continuation), `\`-EOF discards the backslash
> - Add test coverage for these cases and fix incorrect expected values in the JSON test corpus
> - Add `css` test group to allow `vendor/bin/phpunit --group css`
> 
> Note that the css test file diverged from the originals in these cases. For example, [see string/0005](https://github.com/romainmenke/css-tokenizer-tests/blob/4cdf29c796003ce1543b9d86bbf27c3b7447bab3/tests/string/0005/tokens.json) where the expected token value is `foo` like in this PR.
> 
> Also see #226 where bad-string is updated to use `null` token value. These changes will conflict and require an update assuming both are expected to land.
> 
> ## Test plan
> 
> CI passes. Visually confirm that updated and new tests are correct.
> 
>

**Comment by sirreal** [comment]
@copilot [I asked you to update this PR's description.](https://github.com/WordPress/php-toolkit/pull/227#issuecomment-4289997385) [You said it was done but the PR description hasn't actually changed.](https://github.com/WordPress/php-toolkit/pull/227#issuecomment-4290018414)

Please do this as requested.

File: components/DataLiberation/Tests/CSSProcessorTest.php [hunk 7]
```diff
@@ -1542,6 +1544,144 @@ public function test_ident_start_codepoint_bounds_check(): void {
...
+	 * Tests that backslash-newline in a string token contributes nothing to the value.
+	 *
+	 * CSS spec §4.3.5 consume-string-token:
+	 * > U+005C REVERSE SOLIDUS (\)
+	 * > Otherwise, if the next input code point is a newline, consume it.
+	 *
+	 * The backslash and newline are both consumed and produce no value.
+	 *
+	 * @see https://www.w3.org/TR/css-syntax-3/#consume-string-token
+	 * @see https://github.com/WordPress/php-toolkit/issues/222
```
Comment (sirreal) [inline components/DataLiberation/Tests/CSSProcessorTest.php]:
```suggestion
```

File: components/DataLiberation/Tests/CSSProcessorTest.php [hunk 8]
```diff
@@ -1542,6 +1544,144 @@ public function test_ident_start_codepoint_bounds_check(): void {
 		$this->assertSame( $expected_tokens, $actual_tokens );
 	}
 
+	/**
+	 * Tests that backslash-newline in a string token contributes nothing to the value.
+	 *
+	 * CSS spec §4.3.5 consume-string-token:
+	 * > U+005C REVERSE SOLIDUS (\)
+	 * > Otherwise, if the next input code point is a newline, consume it.
```
Comment (sirreal) [inline components/DataLiberation/Tests/CSSProcessorTest.php]:
```suggestion
```

File: components/DataLiberation/Tests/CSSProcessorTest.php [hunk 9]
```diff
@@ -1542,6 +1544,144 @@ public function test_ident_start_codepoint_bounds_check(): void {
...
+			'backslash-CRLF' => array( "'str\\\r\ning'", 'string' ),
+		);
+	}
+
+	/**
+	 * Tests that backslash-EOF in a string token contributes nothing to the value.
+	 *
+	 * CSS spec §4.3.5 consume-string-token:
+	 * > U+005C REVERSE SOLIDUS (\)
+	 * > If the next input code point is EOF, do nothing.
```
Comment (sirreal) [inline components/DataLiberation/Tests/CSSProcessorTest.php]:
```suggestion
```

File: components/DataLiberation/Tests/CSSProcessorTest.php [hunk 10]
```diff
@@ -1542,6 +1544,144 @@ public function test_ident_start_codepoint_bounds_check(): void {
...
+	 *
+	 * The trailing backslash is consumed and produces no value.
+	 *
+	 * @see https://www.w3.org/TR/css-syntax-3/#consume-string-token
+	 * @see https://github.com/WordPress/php-toolkit/issues/223
```
Comment (sirreal) [inline components/DataLiberation/Tests/CSSProcessorTest.php]:
```suggestion
```

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 11]
```diff
@@ -1579,8 +1598,39 @@ private function decode_string_or_url( int $start, int $length ): string {
...
 			if ( '\\' === $char ) {
+				/*
+				 * String tokens have special escape rules per §4.3.5:
+				 * - 0x5C (backslash) at EOF: consume the backslash, produce no value.
+				 * - 0x5C (backslash) followed by 0x0A (LF), 0x0C (FF), or 0x0D (CR):
+				 *   consume both characters as a line continuation, produce no value.
+				 * - 0x5C (backslash) followed by 0x0D 0x0A (CRLF):
+				 *   consume all three characters as a line continuation, produce no value.
+				 * These must be checked before the general escape path.
+				 */
```
Comment (sirreal) [inline components/DataLiberation/CSS/class-cssprocessor.php]:
```suggestion
				/**
				 * String tokens have special escape rules:
				 * - 0x5C (backslash) at EOF: consume the backslash, produce no value.
				 * - 0x5C (backslash) followed by 0x0A (LF), 0x0C (FF), or 0x0D (CR):
				 *   consume both characters as a line continuation, produce no value.
				 * - 0x5C (backslash) followed by 0x0D 0x0A (CRLF):
				 *   consume all three characters as a line continuation, produce no value.
				 * These must be checked before the general escape path.
				 *
				 * @see **https://www.w3.org/TR/css-syntax-3/#consume-string-token
				 */
```

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 12]
```diff
@@ -1537,19 +1548,27 @@ private function consume_ident_start_codepoint( $at ): int {
...
+	 * │ 'x\79z'      │ 'xyz'  │
+	 * │ 'x\000079 z' │ 'xyz'  │
+	 * │ 'a\r\nb'     │ 'a\nb' │
+	 * │ 'a\0b'       │ 'a�b'  │
+	 * └──────────────┴────────┘
+	 *
+	 * @param int  $start           Start byte offset.
+	 * @param int  $length          Length of the substring to decode.
+	 * @param bool $string_escapes  Optional, default false. When true, apply additional escape
+	 *                              rules that apply only to string tokens (CSS §4.3.5).
```
Comment (sirreal) [inline components/DataLiberation/CSS/class-cssprocessor.php]:
```suggestion
	 * @param bool $string_escapes  Optional, default false. When true, apply additional escape
	 *                              rules that apply only to string tokens.
```

**Review by sirreal — COMMENTED** [review]
Add spec link and remove opaque references to spec sections.

File: components/DataLiberation/CSS/class-cssprocessor.php [hunk 13]
```diff
@@ -1579,8 +1598,41 @@ private function decode_string_or_url( int $start, int $length ): string {
...
+				/**
+				 * String tokens have special escape rules:
+				 * - 0x5C (backslash) at EOF: consume the backslash, produce no value.
+				 * - 0x5C (backslash) followed by 0x0A (LF), 0x0C (FF), or 0x0D (CR):
+				 *   consume both characters as a line continuation, produce no value.
+				 * - 0x5C (backslash) followed by 0x0D 0x0A (CRLF):
+				 *   consume all three characters as a line continuation, produce no value.
+				 * These must be checked before the general escape path.
+				 *
+				 * @see **https://www.w3.org/TR/css-syntax-3/#consume-string-token
```
Comment (sirreal) [inline components/DataLiberation/CSS/class-cssprocessor.php]:
```suggestion
				 * @see https://www.w3.org/TR/css-syntax-3/#consume-string-token
```
